# Generated by Django 3.0.8 on 2020-07-18 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trustworthy',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='trustworthy',
        ),
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional information which help informing about this product.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When was this product added to the safemasks portal?'),
        ),
        migrations.AddField(
            model_name='product',
            name='references',
            field=models.TextField(blank=True, help_text='Links and references to crossh-check this product.', null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(-1, 'Negativ'), (0, 'Neutral'), (1, 'Positiv')], default=0, help_text='Is the entry trustworthy? Ranges from -1 (negativ) to +1 (positiv).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional information which help informing about this supplier.', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When was this supplier added to the safemasks portal?'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='references',
            field=models.TextField(blank=True, help_text='Links and references to crossh-check this supplier.', null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When was the review last updated?'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(help_text='What was the product?', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='resources.Product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(help_text='Who submitted this information?', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SupplierReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(help_text='How was this information obtained?')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, help_text='When was the review last updated?')),
                ('rating', models.IntegerField(choices=[(-1, 'Negativ'), (0, 'Neutral'), (1, 'Positiv')], help_text='Is the entry trustworthy? Ranges from -1 (negativ) to +1 (positiv).')),
                ('comment', models.TextField(blank=True, help_text='Additional information to support review.', null=True)),
                ('supplier', models.ForeignKey(help_text='Who is the supplier?', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='resources.Supplier')),
                ('user', models.ForeignKey(help_text='Who submitted this information?', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
