# Generated by Django 3.0.8 on 2020-07-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks_auth', '0005_auto_20200718_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepted_privacy',
            field=models.BooleanField(default=False, help_text='User has accepted safemasks privcacy.', verbose_name='Is reviewed?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='accepted_terms',
            field=models.BooleanField(default=False, help_text='User has accepted safemasks terms and conditions.', verbose_name='Is reviewed?'),
        ),
    ]
