# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'


variables:

  templateAcrPath : ./IaC/acr-template.json
  templatePath : ./IaC/app-template.json
  parametersPath: ./IaC/app-parameters.json
  dockerFileAppPath: ./IaC/Dockerfile

jobs:
  - job: Image
    steps:
    - script: |
        az login --service-principal --username $(spusername) --password $(spuserpassword) --tenant $(Tenant)
        az deployment group create --resource-group $(ResourceGroupACR) --template-file $(templateAcrPath) --parameters RegistryName=$(acrName) --subscription $(Subscription)
        az acr login -n $(acrName) --expose-token
        az acr repository delete --name $(acrName) --image safemasks:app -y
        az acr build -r $(acrName) -f $(dockerFileAppPath) -t safemasks:app . \
        --subscription $(Subscription)

      name: Image
      displayName: 'Build Container Regsitry, Container and Base docker Image'

  - job: Deployment
    dependsOn: Image
    steps:
    - script: |
        az login --service-principal --username $(spusername) --password $(spuserpassword) --tenant $(Tenant)
        az deployment group create --resource-group $(ResourceGroupAPP) --subscription $(Subscription) --template-file $(templatePath) --parameters $(parametersPath) \
        imagePassword=$(imagePassword) \
        SAFEMASKS_ENVIRONMENT=$(SAFEMASKS_ENVIRONMENT) \
        SAFEMASKS_SECRET_KEY=$(SAFEMASKS_SECRET_KEY) \
        SAFEMASKS_DB_BACKEND=$(SAFEMASKS_DB_BACKEND) \
        SAFEMASKS_DB_HOST=$(SAFEMASKS_DB_HOST) \
        SAFEMASKS_DB_NAME=$(SAFEMASKS_DB_NAME) \
        SAFEMASKS_DB_PORT=$(SAFEMASKS_DB_PORT) \
        SAFEMASKS_DB_USER=$(SAFEMASKS_DB_ADMIN_USER) \
        SAFEMASKS_DB_PASSWORD=$(SAFEMASKS_DB_ADMIN_USER_PASSWORD) \
        SAFEMASKS_DB_SSL=$(SAFEMASKS_DB_SSL) \
        SAFEMASKS_HOST=$(SAFEMASKS_HOST)
        SAFEMASKS_EMAIL_BACKEND=$(SAFEMASKS_EMAIL_BACKEND) \
        SAFEMASKS_EMAIL_HOST=$(SAFEMASKS_EMAIL_HOST) \
        SAFEMASKS_EMAIL_HOST_USER=$(SAFEMASKS_EMAIL_HOST_USER) \
        SAFEMASKS_EMAIL_HOST_PASSWORD=$(SAFEMASKS_EMAIL_HOST_PASSWORD) \
        SAFEMASKS_EMAIL_USE_SSL=$(SAFEMASKS_EMAIL_USE_SSL) \
        SAFEMASKS_EMAIL_PORT=$(SAFEMASKS_EMAIL_PORT)
        az container restart --name $(ContainerNameAPP) --resource-group $(ResourceGroupAPP)
      name: Deployment
      displayName: 'Deploy Container with Image'
