# Generated by Django 3.0.5 on 2020-05-15 09:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='+999999999 Up to 15 digits allowed', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('company', models.CharField(blank=True, help_text='Name of your company or institution.', max_length=256, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional information to verify user.', null=True)),
                ('is_reviewed', models.BooleanField(default=False, help_text='Was the authenticity of the user reviewed by the administration?')),
                ('ip', models.GenericIPAddressField(blank=True, help_text='Ip address associated with user.', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time the profile was updated.')),
                ('user', models.OneToOneField(help_text='User instance.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
