# Generated by Django 3.0.5 on 2020-04-20 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of the supplier.', unique=True)),
                ('addresses', models.TextField(blank=True, help_text='Addresses of the supplier. Comma seperated list of URLs or E-Mail addresses.', null=True)),
                ('company_type', models.CharField(choices=[('sup', 'Supplier'), ('man', 'Manufacturer')], max_length=3)),
                ('certificate', models.CharField(help_text='Certificate of the supplier', max_length=128, null=True)),
                ('products', models.ManyToManyField(related_name='suppliers', to='resources.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trustworty', models.BooleanField(help_text='Is the supplier trustworty and fulfills standards?')),
                ('source', models.TextField(help_text='How was this information obtained?')),
                ('date_added', models.DateTimeField(auto_now=True, help_text='When was the review added?')),
                ('supplier', models.ForeignKey(help_text='Who is the supplier?', on_delete=django.db.models.deletion.CASCADE, related_name='appears_in_reviews', to='resources.Supplier')),
                ('user', models.ForeignKey(help_text='Who submitted this information?', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the list.', max_length=128, unique=True)),
                ('suppliers', models.ManyToManyField(help_text='Suppliers contained in the list.', related_name='appears_in_lists', to='resources.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteDataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the resource', max_length=128, unique=True)),
                ('address', models.URLField(help_text='Address of the resource')),
                ('supplements', models.TextField(blank=True, help_text='Additional information about resource.', null=True)),
                ('products', models.ManyToManyField(help_text='About which information does this resource inform?', related_name='appears_in_databases', to='resources.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='How many items were delivered?')),
                ('price_rating', models.IntegerField(choices=[(1, 'low price'), (2, 'fair price'), (3, 'high price')], help_text='Was the price reasonable?')),
                ('date_added', models.DateTimeField(auto_now=True, help_text='When was the review added?')),
                ('product', models.ForeignKey(help_text='Which product was delivered?', on_delete=django.db.models.deletion.CASCADE, to='resources.Product')),
                ('receiver', models.ForeignKey(help_text='Who obtained the delivery?', on_delete=django.db.models.deletion.CASCADE, related_name='obtained_deliveries', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(help_text='Who send out the delivery?', on_delete=django.db.models.deletion.CASCADE, related_name='appears_in_deliveries', to='resources.Supplier')),
            ],
        ),
    ]
