# Generated by Django 3.0.5 on 2020-04-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='date_added',
        ),
        migrations.AddField(
            model_name='productreview',
            name='last_update',
            field=models.DateTimeField(auto_now=True, help_text='When was the review last updated?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('mask', 'Mask'), ('vent', 'Ventilator'), ('sani', 'Sanitizer')], help_text='Name of the product', max_length=4),
        ),
    ]
